In [1]:
import numpy as np

In [2]:
#2nd item to 5th item in 1 gap
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[1:4:2])

[15 25]


In [3]:
#printing everything in 1 gap
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[::2])

[10 20 30 40]


In [6]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
print(arr[1,0]) #2nd row 1st element
print(arr[1,2]) #2nd row 3rd element
print(arr[0,3]) #1st row 4th element

6
8
4


In [21]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.view()
x

array([1, 2, 3, 4, 5])

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
#NumPy method to join two arrays into a single array.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [28]:
#NumPy method to find all items with the value 4.
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
x

(array([3, 5, 6]),)